from .models import Kampus, Jurusan


dataITB =[
"Sarjana (S1) Matematika (MA)",
"Sarjana (S1) Mikrobiologi (BM)",
"Sarjana (S1) Sains dan Teknologi Farmasi (FA)",
"Sarjana (S1) Teknik Geologi (GL)",
"Sarjana (S1) Teknik Pertambangan (TA)",
"Sarjana (S1) Teknik Kimia (TK)",
"Sarjana (S1) Teknik Mesin (MS)",
"Sarjana (S1) Teknik Elektro (EL)",
"Sarjana (S1) Teknik Sipil (SI)",
"Sarjana (S1) Arsitektur (AR)",
"Sarjana (S1) Seni Rupa (SR)",
"Sarjana (S1) Manajemen (MB)",
"Sarjana (S1) Aktuaria (AK)",
"Sarjana (S1) Fisika (FI)",
"Sarjana (S1) Biologi (BI)",
"Sarjana (S1) Farmasi Klinik dan Komunitas (FK)",
"Sarjana (S1) Teknik Perminyakan (TM)",
"Sarjana (S1) Teknik Fisika (TF)",
"Sarjana (S1) Teknik Informatika (IF)",
"Sarjana (S1) Teknik Dirgantara (AE)",
"Sarjana (S1) Teknik Lingkungan (TL)",
"Sarjana (S1) Perencanaan Wilayah dan Kota (PL)",
"Sarjana (S1) Kriya (KR)",
"Sarjana (S1) Kewirausahaan (MK)",
"Sarjana (S1) Astronomi (AS)",
"Sarjana (S1) Rekayasa Hayati (BE)",
"Sarjana (S1) Teknik Geofisika (TG)",
"Sarjana (S1) Meteorologi (ME)",
"Sarjana (S1) Teknik Industri (TI)",
"Sarjana (S1) Teknik Material (MT)",
"Sarjana (S1) Teknik Kelautan (KL)",
"Sarjana (S1) Desain Interior (DI)",
"Sarjana (S1) Teknik Tenaga Listrik (EP)",
"Sarjana (S1) Teknik Pangan (PG)",
"Sarjana (S1) Manajemen Rekayasa (MR)",
"Sarjana (S1) Teknik Bioenergi dan Kemurgi (TB)",
"Sarjana (S1) Kimia (KI)",
"Sarjana (S1) Rekayasa Pertanian (BA)",
"Sarjana (S1) Geofisika (GF)",
"Sarjana (S1) Oseanografi (OS)",
"Sarjana (S1) Rekayasa Infrastruktur Lingkungan (IL)",
"Sarjana (S1) Desain Komunikasi Visual (DK)",
"Sarjana (S1) Teknik Telekomunikasi (ET)",
"Sarjana (S1) Rekayasa Kehutanan (BW)",
"Sarjana (S1) Teknik Metalurgi (MG)",
"Sarjana (S1) Teknik Geodesi dan Geomatika (GD)",
"Sarjana (S1) Teknik dan Pengelolaan Sumber Daya Air (SA)",
"Sarjana (S1) Desain Produk (DP)",
"Sarjana (S1) Sistem dan Teknologi Informasi (II)",
"Sarjana (S1) Teknologi Pasca Panen (PP)",
"Sarjana (S1) Teknik Biomedis (EB)",
"Magister (S2) Matematika (MA)",
"Magister (S2) Biologi (BI)",
"Magister (S2) Farmasi (FA)",
"Magister (S2) Teknik Geologi (GL)",
"Magister (S2) Rekayasa Pertambangan (TA)",
"Magister (S2) Teknik Kimia (TK)",
"Magister (S2) Teknik Mesin (MS)",
"Magister (S2) Teknik Elektro (EL)",
"Magister (S2) Studi Pembangunan (SP)",
"Magister (S2) Teknik Sipil (SI)",
"Magister (S2) Seni Rupa (SR)",
"Magister (S2) Sains Manajemen (MB)",
"Magister (S2) Aktuaria (AK)",
"Magister (S2) Pengajaran Matematika (MA)",
"Magister (S2) Fisika (FI)",
"Magister (S2) Bioteknologi (BT)",
"Magister (S2) Farmasi Industri (FD)",
"Magister (S2) Teknik Perminyakan (TM)",
"Magister (S2) Teknik Fisika (TF)",
"Magister (S2) Informatika (IF)",
"Magister (S2) Teknik Dirgantara (AE)",
"Magister (S2) Transportasi (TR)",
"Magister (S2) Teknik Lingkungan (TL)",
"Magister (S2) Desain (DS)",
"Magister (S2) Administrasi Bisnis (MM)",
"Magister (S2) Pengajaran Fisika (FI)",
"Magister (S2) Astronomi (AS)",
"Magister (S2) Biomanajemen (BP)",
"Magister (S2) Keolahragaan (KO)",
"Magister (S2) Teknik Geofisika (TG)",
"Magister (S2) Sains Kebumian (SB)",
"Magister (S2) Ilmu dan Teknik Material (MT)",
"Magister (S2) Instrumentasi dan Kontrol (IK)",
"Magister (S2) Teknik Kelautan (KL)",
"Magister (S2) Perencanaan Kepariwisataan (PK)",
"Magister (S2) Administrasi Bisnis (Kampus Jakarta) (MM)",
"Magister (S2) Kimia (KI)",
"Magister (S2) Teknik Metalurgi (MG)",
"Magister (S2) Teknik Air Tanah (AT)",
"Magister (S2) Teknik dan Manajemen Industri (TI)",
"Magister (S2) Ilmu dan Rekayasa Nuklir (RN)",
"Magister (S2) Arsitektur (AR)",
"Magister (S2) Pengelolaan Infrastruktur Air Bersih dan Sanitasi (IS)",
"Magister (S2) Pengajaran Kimia (KI)",
"Magister (S2) Sains Komputasi (SK)",
"Magister (S2) Teknik Geotermal (PB)",
"Magister (S2) Teknik Geodesi dan Geomatika (GD)",
"Magister (S2) Rancang Kota (RK)",
"Magister (S2) Pengelolaan Sumberdaya Air (PSDA) (SA)",
"Magister (S2) Logistik (LO)",
"Magister (S2) Perencanaan Wilayah dan Kota (PL)",
"Magister (S2) Sistem dan Teknik Jalan Raya (SJ)",
"Magister (S2) Arsitektur Lanskap (AL)",
"Magister (S2) Teknologi Nano (NT)",
"Doktor (S3) Matematika (MA)",
"Doktor (S3) Biologi (BI)",
"Doktor (S3) Farmasi (FA)",
"Doktor (S3) Teknik Geologi (GL)",
"Doktor (S3) Rekayasa Pertambangan (TA)",
"Doktor (S3) Teknik Kimia (TK)",
"Doktor (S3) Teknik Mesin (MS)",
"Doktor (S3) Teknik Elektro dan Informatika (EI)",
"Doktor (S3) Transportasi (TR)",
"Doktor (S3) Teknik Sipil (SI)",
"Doktor (S3) Ilmu Seni Rupa dan Desain (SD)",
"Doktor (S3) Sains Manajemen (MB)",
"Doktor (S3) Fisika (FI)",
"Doktor (S3) Teknik Fisika (TF)",
"Doktor (S3) Teknik Dirgantara (AE)",
"Doktor (S3) Arsitektur (AR)",
"Doktor (S3) Teknik Lingkungan (TL)",
"Doktor (S3) Astronomi (AS)",
"Doktor (S3) Teknik Perminyakan (TM)",
"Doktor (S3) Sains Kebumian (SB)",
"Doktor (S3) Teknik dan Manajemen Industri (TI)",
"Doktor (S3) Ilmu dan Teknik Material (MT)",
"Doktor (S3) Perencanaan Wilayah dan Kota (PL)",
"Doktor (S3) Kimia (KI)",
"Doktor (S3) Teknik Geofisika (TG)",
"Doktor (S3) Rekayasa Nuklir (RN)",
"Doktor (S3) Teknik Geodesi dan Geomatika (GD)",
"Doktor (S3) Sains dan Teknologi Nano (NT)"
]

dataTelkom = [
"Sarjana (S1) Teknik Telekomunikasi",
"Sarjana (S1) Teknik Elektro",
"Sarjana (S1) Teknik Fisika",
"Sarjana (S1) Teknik Komputer",
"Sarjana (S1) Teknik Biomedis",
"Pascasarjana (S2) Teknik Elektro",
"Sarjana (S1) Teknik Industri",
"Sarjana (S1) Sistem Informasi",
"Sarjana (S1)Teknik Logistik",
"Pascasarjana (S2) Teknik Industri",
"Pascasarjana (S2) Sistem Informasi",
"Sarjana (S1) Informatika",
"Sarjana (S1) Teknologi Informasi",
"Sarjana (S1) Rekayasa Perangkat Lunak",
"Sarjana (S1) PJJ Informatika",
"Sarjana (S1) Sains Data",
"Pascasarjana (S2) Informatika",
"Pascasarjana (S2) Ilmu Forensik",
"Pascasarjana (S3) Informatika",
"Sarjana (S1) Manajemen Bisnis Telekomunikasi Informatika",
"Sarjana (S1) Akuntansi",
"Pascasarjana (S2) Manajemen",
"Pascasarjana (S2) PJJ Manajemen",
"Sarjana (S1) Administrasi Bisnis",
"Sarjana (S1) Ilmu Komunikasi",
"Sarjana (S1) Hubungan Masyarakat Digital",
"Sarjana (S1) Desain Komunikasi Visual",
"Sarjana (S1) Desain Produk",
"Sarjana (S1) Desain Interior",
"Sarjana (S1) Kriya Tekstil dan Fashion",
"Sarjana (S1) Seni Rupa",
"Pascasarjana (S2) Desain",
"D3 Teknologi Telekomunikasi",
"D3 Rekayasa Perangkat Lunak Aplikasi",
"D3 Sistem Informasi",
"D3 Sistem Informasi Akuntansi",
"D3 Teknologi Komputer",
"D3 Manajemen Pemasaran",
"D3 Perhotelan",
"D4 Teknologi Rekayasa Multimedia"]

dataUnpad =[
"Sarjana (S1) Ilmu Hukum",
"Sarjana (S1) Akuntansi",
"Sarjana (S1) Ilmu Ekonomi",
"Sarjana (S1) Manajemen",
"Sarjana (S1) Ekonomi Islam",
"Sarjana (S1) Bisnis Digital",
"Sarjana (S1) Kedokteran",
"Sarjana (S1) Kedokteran Hewan",
"Sarjana (S1) Matematika",
"Sarjana (S1) Kimia",
"Sarjana (S1) Fisika",
"Sarjana (S1) Biologi",
"Sarjana (S1) Statistika",
"Sarjana (S1) Geofisika",
"Sarjana (S1) Teknik Informatika",
"Sarjana (S1) Teknik Elektro",
"Sarjana (S1) Aktuaria",
"Sarjana (S1) Agroteknologi",
"Sarjana (S1) Agribisnis",
"Sarjana (S1) Kedokteran Gigi",
"Sarjana (S1) Administrasi Publik",
"Sarjana (S1) Hubungan Internasional",
"Sarjana (S1) Kesejahteraan Sosial",
"Sarjana (S1) Ilmu Pemerintahan",
"Sarjana (S1) Antropologi",
"Sarjana (S1) Administrasi Bisnis",
"Sarjana (S1) Sosiologi",
"Sarjana (S1) Ilmu Politik",
"Sarjana (S1) Sastra Indonesia",
"Sarjana (S1) Sastra Sunda",
"Sarjana (S1) Ilmu Sejarah",
"Sarjana (S1) Sastra Inggris",
"Sarjana (S1) Sastra Perancis",
"Sarjana (S1) Sastra Jepang",
"Sarjana (S1) Sastra Rusia",
"Sarjana (S1) Sastra Jerman",
"Sarjana (S1) Sastra Arab",
"Sarjana (S1) Psikologi",
"Sarjana (S1) Peternakan",
"Sarjana (S1) Ilmu Komunikasi",
"Sarjana (S1) Perpustakaan dan Sains Informasi",
"Sarjana (S1) Hubungan Masyarakat",
"Sarjana (S1) Jurnalistik",
"Sarjana (S1) Manajemen Komunikasi",
"Sarjana (S1) Televisi dan Film",
"Sarjana (S1) Keperawatan",
"Sarjana (S1) Perikanan",
"Sarjana (S1) Ilmu Kelautan",
"Sarjana (S1) Teknik Pertanian",
"Sarjana (S1) Teknologi Pangan",
"Sarjana (S1) Teknologi Industri Pertanian",
"Sarjana (S1) Farmasi",
"Sarjana (S1) Teknik Geologi",
"Magister (S2) Ilmu Hukum",
"Magister (S2) Kenotariatan",
"Magister (S2) Ekonomi",
"Magister (S2) Ilmu Ekonomi",
"Magister (S2) Ilmu Manajemen",
"Magister (S2) Manajemen",
"Magister (S2) Akuntansi",
"Magister (S2) Ekonomi Terapan",
"Magister (S2) Manajemen",
"Magister (S2) Manajemen Mikro Terpadu",
"Magister (S2) Ilmu Kedokteran Dasar",
"Magister (S2) Ilmu Kesehatan Masyarakat",
"Magister (S2) Kebidanan",
"Magister (S2) Anti Aging dan Aesthetic Medicine",
"Magister (S2) Epidemiologi",
"Magister (S2) Ilmu Kimia",
"Magister (S2) Statistika Terapan",
"Magister (S2) Matematika",
"Magister (S2) Biologi",
"Magister (S2) Fisika",
"Magister (S2) Ekonomi Pertanian",
"Magister (S2) Ilmu Tanah",
"Magister (S2) Agronomi",
"Magister (S2) Administrasi Publik",
"Magister (S2) Administrasi Bisnis",
"Magister (S2) Ilmu Antropologi",
"Magister (S2) Sosiologi",
"Magister (S2) Ilmu Kesejahteraan Sosial",
"Magister (S2) Kebijakan Publik",
"Magister (S2) Ilmu Politik",
"Magister (S2) Ilmu Pemerintahan",
"Magister (S2) Ilmu Sastra",
"Magister (S2) Kajian Budaya",
"Magister (S2) Ilmu Linguistik",
"Magister (S2) Sejarah",
"Magister (S2) Ilmu Peternakan",
"Magister (S2) Ilmu Komunikasi",
"Magister (S2) Magister Ilmu Keperawatan",
"Magister (S2) Teknologi Industri Pertanian",
"Magister (S2) Teknologi Agroindustri",
"Magister (S2) Farmasi",
"Magister (S2) Farmasi Klinik",
"Magister (S2) Teknik Geologi",
"Magister (S2) Ilmu Lingkungan",
"Magister (S2) Ilmu Keberlanjutan",
"Magister (S2) Pariwisata Berkelanjutan",
"Magister (S2) Bioteknologi",
"Magister (S2) Inovasi Regional",
"Magister (S2) Manajemen Sumberdaya Hayati",
"Doktor (S3) Ekonomi",
"Doktor (S3) Manajemen",
"Doktor (S3) Akuntansi",
"Doktor (S3) Ilmu Kedokteran",
"Doktor (S3) Ilmu Kimia",
"Doktor (S3) Matematika",
"Doktor (S3) Ilmu Pertanian",
"Doktor (S3) Sosiologi",
"Doktor (S3) Ilmu Administrasi",
"Doktor (S3) Hubungan Internasional",
"Doktor (S3) Kesejahteraan Sosial",
"Doktor (S3) Ilmu Sastra",
"Doktor (S3) Ilmu Psikologi",
"Doktor (S3) Ilmu Peternakan",
"Doktor (S3) Ilmu Komunikasi",
"Doktor (S3) Farmasi",
"Doktor (S3) Ilmu Lingkungan",
"Doktor (S3) Bioteknologi",
"D-IV Akuntansi Perpajakan",
"D-IV Akuntansi Sektor Publik",
"D-IV Bisnis Internasional",
"D-IV Pemasaran Digital",
"D-IV Kebidanan",
"D-IV Agroteknopreneur",
"D-IV Administrasi Pemerintahan",
"D-IV Administrasi Keuangan Publik",
"D-IV Bisnis Logistik",
"D-IV Kearsipan Digital",
"D-IV Bahasa dan Budaya Tiongkok",
"D-IV Manajemen Produksi Media",
"D-IV Pariwisata Bahari"
]


dataUnpar =[
"Sarjana (S1) Ekonomi Pembangunan",
"Sarjana (S1) Manajemen",
"Sarjana (S1) Akuntansi",
"Sarjana (S1) Teknik Sipil",
"Sarjana (S1) Arsitektur",
"Sarjana (S1) Teknik Elektro",
"Sarjana (S1) Teknik Kimia ",
"Sarjana (S1) Teknik Industri",
"Sarjana (S1) Ilmu Administrasi Publik",
"Sarjana (S1) Ilmu Administrasi Bisnis",
"Sarjana (S1) Ilmu Hubungan Internasional",
"Sarjana (S1) Fisika",
"Sarjana (S1) Matematika",
"Sarjana (S1) Teknik Informatika",
"Sarjana (S1) Ilmu Hukum",
"Sarjana (S1) Ilmu Filsafat",
"Magister (S2) Manajemen ",
"Magister (S2) Teknik Sipil",
"Magister (S2) Arsitektur",
"Magister (S2) Teknik Kimia",
"Magister (S2) Teknik Industri",
"Magister (S2) Ilmu Administrasi Bisnis",
"Magister (S2) Ilmu Hubungan Internasional",
"Magister (S2) Ilmu Hukum",
"Magister (S2) Ilmu Teologi",
"Doktor  (S3) Ilmu Ekonomi",
"Doktor  (S3) Teknik Sipil",
"Doktor  (S3) Arsitektur",
"Doktor  (S3) Ilmu Hukum",
"Diploma III Manajemen Perusahaan"
]

listKampus = [
    "Institut Teknologi Bandung (ITB)",
    "Universitas Padjadjaran (UNPAD)",
    "Telkom University (Tel-U)",
    "Universitas Katolik Parahyangan"


]
dataKampus ={"Institut Teknologi Bandung (ITB)":dataITB,
"Universitas Padjadjaran (UNPAD)":dataUnpad,
"Telkom University (Tel-U)":dataTelkom,
"Universitas Katolik Parahyangan":dataUnpar}
    

def updateKampus():
    for data in listKampus:
        Kampus.objects.create(
            nama = data
        )

def updateJurusan():
    for data in listKampus:
        kampus = Kampus.objects.get(nama=data)
        for datajurusan in dataKampus[data]:
            Jurusan.objects.create(
                kampus = kampus,
                jurusan = datajurusan
            )