# Generated by Django 3.2.8 on 2021-12-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='infoKontak',
        ),
        migrations.AddField(
            model_name='infouser',
            name='isEmail',
            field=models.CharField(choices=[('False', 'false'), ('True', 'true')], default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='infouser',
            name='isLine',
            field=models.CharField(choices=[('False', 'false'), ('True', 'true')], default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='infouser',
            name='isTelponSms',
            field=models.CharField(choices=[('False', 'false'), ('True', 'true')], default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='infouser',
            name='isWa',
            field=models.CharField(choices=[('False', 'false'), ('True', 'true')], default='False', max_length=100),
        ),
    ]
