# Generated by Django 4.0 on 2022-01-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211227_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
