# Generated by Django 4.0 on 2022-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_infouser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
