# Generated by Django 4.0 on 2022-01-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_infouser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='kampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.CharField(max_length=255)),
                ('kampus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kampus')),
            ],
        ),
    ]
